script: lkan.scripts.train
model: lkan.models.KAN
model_params:
  layers_dims:
  - 784
  - 11
  - 10
  grid_size: 5
  k: 3
  noise_scale: 0.1
  noise_scale_base: 0.1
  scale_spline: 1.0
  base_fun: silu
  grid_eps: 1.0
  grid_range:
  - -1
  - 1
  bias_trainable: true
  sp_trainable: true
  sb_trainable: true
  kan_layer_version: normal
  device: ${trainer_params.device}
trainer: lkan.trainers.ImgKANTrainer
trainer_params:
  lr: 0.0003
  update_grid: false
  grid_update_freq: 4
  stop_grid_update_step: 100
  lr_step: null
  clip_grad_norm: 0.5
  accumulate_grad_batches: 1
  device: cuda
lr_scheduler: null
lr_scheduler_params: null
train_params:
  max_epochs: 30
  max_steps: 10000
  validation_every_n_steps: 100
  save_every_n_steps: 2500
datamodule: lkan.datamodule.MNISTDataModule
datamodule_params:
  batch_size: 50
  split_ratio: 0.8
  root: ./.data
  input_size: 28
save_dir: ./.experiments/mnistkan/v1
name: mnistkan
version: v1
