script: lkan.scripts.train
model: lkan.models.KAN
model_params:
  layers_dims: [2,5,1]
  grid_size: 5
  k: 3
  noise_scale: 0.1
  noise_scale_base: 0.1
  scale_spline: 1.0 # float or null (null only for version b)
  base_fun: silu
  grid_eps: 1.0
  grid_range: [-1, 1]
  bias_trainable: true
  sp_trainable: true
  sb_trainable: true
  kan_layer_version: normal
  device: ${trainer_params.device}
trainer: lkan.trainers.BasicKANTrainer
trainer_params:
    lr: 0.001
    update_grid: true
    grid_update_freq: 63
    stop_grid_update_step: 10000
    lr_step: null
    clip_grad_norm: 0.5
    accumulate_grad_batches: 1
    device: cuda
lr_scheduler: null
lr_scheduler_params: null
train_params:
  max_epochs: 10
  max_steps: 10000
  validation_every_n_steps: 100
  save_every_n_steps: 2500
datamodule: lkan.datamodule.TestDataModule
datamodule_params:
  batch_size: 64
  split_ratio: 0.8
save_dir: ./.experiments/${name}/${version}
name: basickan
version: v1