script: lkan.scripts.train
model: lkan.models.MLP
logger: lkan.loggers.TensorBoardLogger
logger_params: {}
model_params:
  layers_dims: [784,128,10]
  device: ${trainer_params.device}
trainer: lkan.trainers.ImgMLPTrainer
trainer_params:
    lr: 3e-4
    lr_step: null
    clip_grad_norm: 0.5
    accumulate_grad_batches: 1
    device: cuda
lr_scheduler: null
lr_scheduler_params: null
train_params:
  max_epochs: 30
  max_steps: 10000
  validation_every_n_steps: 100
  save_every_n_steps: 2500
datamodule: lkan.datamodule.MNISTDataModule
datamodule_params:
  batch_size: 50
  split_ratio: 0.8
  root: ./.data
  input_size: 28
save_dir: ./.experiments/${name}/${version}
name: mnist_mlp
version: v1